[api]
x_bearer_token = "AAAAAAAAAAAAAAAAAAAAAEta4AEAAAAA7CBn8hhm9PqwZQ39A0nBR78%2FBHg%3D0qV6OHFAT8kUTgPXCguqJqZTWtMM96lyhfsYDhK8vxLTO9VDnn"
telegram_bot_token = "7753192183:AAHiYwcP2NFBi-VgTJ90ehK9FKzkFudT-7U"
app_password = "NeroCar123@"
team_passwords = {}